name: Update Scope Node Dependencies
branding:
  icon: package
  color: blue
description: Updates Node dependencies within a scope and creates a pull request with the changes.
inputs:
  commit-message-prefix:
    description: Prefix to use for commit messages.
    default: chore
  git-user-email:
    description: Git user.email to use for the commit.
    default: 41898282+github-actions[bot]@users.noreply.github.com
  git-user-name:
    description: Git user.name to use for the commit.
    default: github-actions[bot]
  npm-registry-scope:
    description: NPM registry scope
    required: true
  npm-registry-url:
    description: NPM registry to used for scope defined in `npm-registry-scope`. Must start with https://.
    required: true
  pre-commit-script:
    description: A command to run before committing the dependency changes (e.g. npm run build).
  pull-request-labels:
    description: Comma-delimited labels to apply to the pull request.
    default: dependencies
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.git-user-name }}
    - ${{ inputs.git-user-email }}
    - ${{ inputs.pre-commit-script }}
    - ${{ inputs.pull-request-labels }}
    - ${{ inputs.commit-message-prefix }}
    - ${{ inputs.npm-registry-scope }}
    - ${{ inputs.npm-registry-url }}
